=== rod8902/hanyang/RTI/ndds.5.1.0/resource/rtiddsgen/xml/generationInfo.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--

(c) Copyright, Real-Time Innovations, Inc. 2003-2010.  All rights reserved.

Modification history
- - - - - - - - - - - - -
5.0.1,06may13,fcs CODEGEN-584: Received samples for an Extensible type may 
                  contain invalid values for fields not present on the wire
5.01,30apr13,acr CODEGEN-574 Added allocate generation mode and removed
                 optional attribute (we don't need separate templates for
                 optional members anymore; we re-use existing ones)
5.01,24apr13,acr CODEGEN-574 Added optional attribute to templates and new
                 generation mode for the finalizeOptionalMembers function.
10ae,10feb11,fcs Fixed bug 13844
10ae,05aug10,rbw Added missing sequenceActualSizeMethod to avoid validation
                 errors (already being used in generation-info)
10ab,03jun09,rbw Updated to match current contents of generation-info.java.xml
10x,09may08,rbw Added multidim attribute for multi-dimensional arrays
10v,19mar08,rbw Added missing methods
10v,17mar08,rbw Added missing methods
10v,11mar08,rbw Allow distinguishing between user enums and user structs
10s,04mar08,rbw Added cdrType attribute to support CDR in C++/CLI
10o,03jul07,rbw Updated for new attributes in file format
10m,11jul06,krb Added attribute 'special' to element 'kind' so that
                parallel templates can exist for special purpose types.
10e,19apr05,rw  Updated attribute list to reflect changes to
                generation-info.*.xml
10e,28mar05,rw  Bug #10270: removed copy_key_fields (unified with copy)
10e,22mar05,rw  Updated to reflect changes to generation-info.*.xml
10d,15nov04,eys Type plugin refactoring
10d,26jul04,rw  Added method kind "copy_key_fields"
10d,22jul04,rw  Refactored from generation-info.*.xml
-->


<!-- ===================================================================== -->
<!-- Entities                                                              -->
<!-- ===================================================================== -->

<!ENTITY nl "&#xa;">                <!--   new line  -->
<!ENTITY indent "    ">             <!-- indentation -->


<!-- ===================================================================== -->
<!-- Elements                                                              -->
<!-- ===================================================================== -->

<!ELEMENT generationInfo (typeInfoMap, methodInfoMap, sourcePreamble+)>
<!ATTLIST generationInfo style    NMTOKEN #IMPLIED
                         language NMTOKEN #REQUIRED>

<!ELEMENT typeInfoMap (type*)>

<!ELEMENT type EMPTY>
<!ATTLIST type idlType                   NMTOKEN #REQUIRED
               nativeType                NMTOKEN #REQUIRED
               initialValue              CDATA   #IMPLIED
               cdrType                   NMTOKEN #IMPLIED
               typeCode                  NMTOKEN #REQUIRED
               corbaCPPNativeType        NMTOKEN #IMPLIED
               nativeTypeSeq             NMTOKEN #REQUIRED
               typeEnum                  CDATA   #REQUIRED
               class					 NMTOKEN #IMPLIED

               elementSerializeMethod    NMTOKEN #REQUIRED
               arraySerializeMethod      NMTOKEN #REQUIRED
               sequenceSerializeMethod   NMTOKEN #REQUIRED
               pointerSequenceSerializeMethod    NMTOKEN #IMPLIED

               elementDeserializeMethod  NMTOKEN #REQUIRED
               arrayDeserializeMethod    NMTOKEN #REQUIRED
               sequenceDeserializeMethod NMTOKEN #REQUIRED
               pointerSequenceDeserializeMethod  NMTOKEN #IMPLIED

               elementSkipMethod         NMTOKEN #IMPLIED
               arraySkipMethod           NMTOKEN #IMPLIED
               sequenceSkipMethod        NMTOKEN #IMPLIED
               pointerSequenceSkipMethod NMTOKEN #IMPLIED

               elementPrintMethod        NMTOKEN #IMPLIED
               elementPrintBitsMethod    NMTOKEN #IMPLIED

               elementInitMethod         NMTOKEN #IMPLIED

               elementCopyMethod         NMTOKEN #IMPLIED

               elementSize               CDATA   #REQUIRED
               elementAlignment          NMTOKEN #REQUIRED
               elementSizeMethod         CDATA   #REQUIRED
               arraySizeMethod           CDATA   #REQUIRED
               sequenceSizeMethod        CDATA   #REQUIRED
               sequenceActualSizeMethod  CDATA   #REQUIRED
>

<!ELEMENT methodInfoMap (method*)>

<!ELEMENT method (template*)>
<!ATTLIST method kind (structMember            |
                       serialize               |
                       deserialize             |
                       skip                    |
                       get_min_size_serialized |
                       get_max_size_serialized |
                       print                   |
                       copy                    |
                       initialize              |
                       finalize                |
                       finalize_optional       |
                       allocate                |
                       new                     |
                       nativeType              |
                       hashCode                |
                       equals)                   #REQUIRED
>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template kind (scalar | string | wstring | array | sequence |
                         bitfield | arraySequence)  #REQUIRED
                   baseMemberKind (scalar | string | wstring | array | 
                         sequence | bitfield | arraySequence) #IMPLIED
                   typeKind (builtin | user)        #IMPLIED
                   optional (true | false)              #IMPLIED
                   pointer  (yes | no)              #IMPLIED
                   bitKind  (normal | lastBitField) #IMPLIED
                   type     (string  |
                             wstring |
                             wchar   |
                             boolean)               #IMPLIED
                   enum     (yes | no)              #IMPLIED
                   multidim (yes | no)              #IMPLIED
                   special  (none | corba_union)    "none"
>

<!ELEMENT sourcePreamble (#PCDATA)>
<!ATTLIST sourcePreamble kind (type-header | type-source | support-header |
                               support-source | type-plugin-header |
                               type-plugin-source | type-datatype-source |
                               java) #IMPLIED
>

=== rod8902/hanyang/RTI/ndds.5.1.0/resource/rtiddsgen/xml/generation-info.java.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE generationInfo SYSTEM "generationInfo.dtd" [
<!ENTITY namespaceSeperator ".">    <!-- namespace separator -->
]>

<!-- 

(c) Copyright, Real-Time Innovations, Inc. 2003-2010.  All rights reserved.

Modification history
- - - - - - - - - - - - -
5.0.1,10jun13,fcs CODEGEN-596: TypePlugin code generation for optional members in Java
5.0.1,18may13,fcs CODEGEN-590: Deserialization of sequences whose length exceeds 
                  the maximum allowed does not produce an error
5.0.1,06may13,fcs CODEGEN-584: Received samples for an Extensible type may 
                  contain invalid values for fields not present on the wire
5.0.1,06may13,fcs CODEGEN-585: Fixed false positives in equal method
5.0.1,04may13,fcs CODEGEN-560: XTypes mutability support in Java
5.0.1,03may13,fcs CODEGEN-551: Incorrect current_alignment for 
                  get_serialized_sample_size method for mutable_types
4.5e, 08aug11,acr Enforce sequence max length (bug #14051)
1.0ac,06dec10,fcs Fixed bug 13780
1.0ac,08nov09,fcs Fixed sequenceActualSizeMethod for WCHAR
1.0ac,20aug09,fcs Removed CDR_NATIVE usage
1.0ac,10aug09,fcs get_serialized_sample_size support
10ab,03jun09,rbw Reflected new sequence types
10u,24apr08,fcs Added hashCode
10s,11mar08,rbw Eliminated unnecessary string allocations
10s,04mar08,fcs Added new imports to sourcePreamble
10s,29feb08,fcs Support for get_min_size_serialized
10s,18feb08,fcs MD5 KeyHash generation support
10s,18feb08,fcs Skip support
10p,12jan08,eys Fixed sequence deserialize
10p,11jul07,eh  Refactor data encapsulation to support previous nddsgen-generated plugins;
                use existing (de)serialize() prototype when add data encapsulation header
10m,06apr07,fcs Fixed multidimensional array copy
10m,25mar07,kaj Add serializeOption for TypeSupportQosPolicy
10m,24oct06,jml Added TypeSupportType import.
10m,20ago06,jml Changed char mapping to char. Bug #11124 
				Changed class field for typeInfoMap in char and wchar.Bug #11262
10l,18aug06,krb Reduced the arraySequence cases for copy 
                and simplified bit field copy routine.
10l,16aug06,krb Reworked some of the copy functionality.
10l,14aug06,krb Added copy functionality (filed as bug 11000)
                Also fixed bug 11154 (arraySequences not generating
                equals() method correctly).
10l,11aug06,fcs Added nativeType method
10l,10aug06,fcs Added class attribute to typeInfoMap
10l,20apr06,fcs Fixed bug 10957
10h,13dec05,fcs The Object returned by the function create is casted
                to the corresponding specific type        
10h,13dec05,fcs Value type support        
10f,17aug05,fcs Removed X in the calls to TypeSupport
10f,20jul05,fcs Removed unnecessary source preambles.
10f,19jul05,fcs Changed primitive builtin type code names.
10f,27jun05,fcs Added type code variable for primitive types
10c,29mar05,fcs Refactored to support:
                - Bitfields
                - Sequences and Arrays of strings
                - Long Double with a CDR representation of 128 bits
                - ...
10e,28mar05,rw  Fixed mis-named method template
10b,16nov04,rw  Bug #9680: separate methods for string/wstring
                max serialized size
10d,07sep04,rw  Replaced import of BuiltinTopicKey_t with InstanceId_t
10d,26aug04,rw  Added import for BuiltinTopicKey_t
10d,16aug04,rw  Changed some method names
10d,22jul04,rw  Updated method names to match DDS conventions; refactored
                out DTD to separate file
10c,26may04,rrl Replaced tabs with 4 spaces to make output look prettier
10c,24may04,rrl Fixed bug in printing sequences
10c,24may04,rrl Improved toString() printing
10c,17may04,rw  More (unsigned) long fixes
10c,17may04,rrl Fixed (unsigned) int/long mappings to ensure Java-C/C++ compatibility.
40b,04may04,rrl Modified initialization to use create() method instead of "new"
                (to support enums, which do not have a public ctor).
40b,03may04,rrl Added support for equals() and testsuite directed changes.
40b,26apr04,rrl Modifications to support new deserialize_objectX() API and enum support
                as well as API changes in TypeSupportImpl from *I() to *X()
40b,21apr04,rrl Support sequences
40b,15mar04,rrl Created
-->

<generationInfo style="RTI" language="Java">
    <typeInfoMap>
               
        <type idlType="short" nativeType="short" 
                   initialValue="0"
                   class="Short"
                   typeCode="TypeCode.TC_SHORT"                   
                   nativeTypeSeq="ShortSeq"
                   typeEnum="CdrPrimitiveType.SHORT"
                   elementSerializeMethod="writeShort"
                   arraySerializeMethod="writeShortArray"
                   sequenceSerializeMethod="writeShortSeq"
                   elementDeserializeMethod="readShort"
                   arrayDeserializeMethod="readShortArray"
                   sequenceDeserializeMethod="readShortSequence"
                   elementSkipMethod="skipShort"
                   arraySkipMethod="skipShortArray"
                   sequenceSkipMethod="skipShortSequence"
                   elementSize="CdrPrimitiveType.SHORT.size"
                   elementAlignment="CdrPrimitiveType.SHORT.alignment"
                   elementSizeMethod="CdrPrimitiveType.SHORT.getMaxSizeSerialized"
                   arraySizeMethod="CdrPrimitiveType.SHORT.getArrayMaxSizeSerialized"                
                   sequenceSizeMethod="CdrPrimitiveType.SHORT.getSequenceMaxSizeSerialized"
                   sequenceActualSizeMethod="CdrPrimitiveType.SHORT.getSequenceSerializedSize"/>  

        <type idlType="long" nativeType="int" 
                   initialValue="0"
                   class="Integer"
                   typeCode="TypeCode.TC_LONG"
                   nativeTypeSeq="IntSeq"
                   typeEnum="CdrPrimitiveType.INT"
                   elementSerializeMethod="writeInt"
                   arraySerializeMethod="writeIntArray"
                   sequenceSerializeMethod="writeIntSeq"
                   elementDeserializeMethod="readInt"
                   arrayDeserializeMethod="readIntArray"
                   sequenceDeserializeMethod="readIntSequence"
                   elementSkipMethod="skipInt"
                   arraySkipMethod="skipIntArray"
                   sequenceSkipMethod="skipIntSequence"
                   elementSize="CdrPrimitiveType.INT.size"
                   elementAlignment="CdrPrimitiveType.INT.alignment"
                   elementSizeMethod="CdrPrimitiveType.INT.getMaxSizeSerialized"
                   arraySizeMethod="CdrPrimitiveType.INT.getArrayMaxSizeSerialized"      
                   sequenceSizeMethod="CdrPrimitiveType.INT.getSequenceMaxSizeSerialized"
                   sequenceActualSizeMethod="CdrPrimitiveType.INT.getSequenceSerializedSize"/>   

        <type idlType="longlong" nativeType="long" 
                   initialValue="0"
                   class="Long"
                   typeCode="TypeCode.TC_LONGLONG"
                   nativeTypeSeq="LongSeq"
                   typeEnum="CdrPrimitiveType.LONG"
                   elementSerializeMethod="writeLong"
                   arraySerializeMethod="writeLongArray"
                   sequenceSerializeMethod="writeLongSeq"
                   elementDeserializeMethod="readLong"
                   arrayDeserializeMethod="readLongArray"
                   sequenceDeserializeMethod="readLongSequence"
                   elementSkipMethod="skipLong"
                   arraySkipMethod="skipLongArray"
                   sequenceSkipMethod="skipLongSequence"
                   elementSize="CdrPrimitiveType.LONG.size"
                   elementAlignment="CdrPrimitiveType.LONG.alignment"
                   elementSizeMethod="CdrPrimitiveType.LONG.getMaxSizeSerialized"
                   arraySizeMethod="CdrPrimitiveType.LONG.getArrayMaxSizeSerialized"                
                   sequenceSizeMethod="CdrPrimitiveType.LONG.getSequenceMaxSizeSerialized"
                   sequenceActualSizeMethod="CdrPrimitiveType.LONG.getSequenceSerializedSize"/>   

        <type idlType="unsignedshort" nativeType="short" 
                   initialValue="0"
                   class="Short"
                   typeCode="TypeCode.TC_USHORT"                                                 
                   nativeTypeSeq="ShortSeq"
                   typeEnum="CdrPrimitiveType.SHORT"
                   elementSerializeMethod="writeShort"
                   arraySerializeMethod="writeShortArray"
                   sequenceSerializeMethod="writeShortSeq"
                   elementDeserializeMethod="readShort"
                   arrayDeserializeMethod="readShortArray"
                   sequenceDeserializeMethod="readShortSequence"
                   elementSkipMethod="skipShort"
                   arraySkipMethod="skipShortArray"
                   sequenceSkipMethod="skipShortSequence"
                   elementSize="CdrPrimitiveType.SHORT.size"
                   elementAlignment="CdrPrimitiveType.SHORT.alignment"
                   elementSizeMethod="CdrPrimitiveType.SHORT.getMaxSizeSerialized"
                   arraySizeMethod="CdrPrimitiveType.SHORT.getArrayMaxSizeSerialized"                
                   sequenceSizeMethod="CdrPrimitiveType.SHORT.getSequenceMaxSizeSerialized"
                   sequenceActualSizeMethod="CdrPrimitiveType.SHORT.getSequenceSerializedSize"/>


        <!-- Note that unsignedling is mapped to native 'int'. This way we keep
             on the wire format compatible with C/C++ to ensure compatibility.
             The governing principle is 
             
             We should warn on use of unsigned members while transforming IDL to
             Java. Being filed as a bug...
        -->
                                      
        <type idlType="unsignedlong" nativeType="int" 
                   initialValue="0"
